#!/usr/bin/env bash
# coding=utf-8
#
# Print output generated by the Star Distance application.
#
# This script is specific to lemuria.cis.vtc.edu.
set -euo pipefail

hadoop fs -cat "star-distance-${1}/part-r-00000"
