#!/usr/bin/env bash
# coding=utf-8
#
# Delete output generated by the Star Distance application.
#
# This script is specific to lemuria.cis.vtc.edu.
set -euo pipefail

hadoop fs -rm -r "star-distance-${1}"
